### ISSUE TITLE
observability (cdc) improve observability of changfeed 

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tiflow#10342]
### How to define the observability of a changfeed

Recently one of CDC user encountered a sink-to-mysql stuck issue, we can't locate even guess the root cause from existing metrics/grafana. So I walked through the sink-to-mysql code comprehensively, and found a potential stuck issue https://github.com/pingcap/tiflow/issues/10334 and workload skew issue https://github.com/pingcap/tiflow/issues/10341 . But we have no way to judge if the user's issue is what we have found. We need a better end to end observability for different changfeeds. For example we need to know how many events/messages cached/buffered/piled up in each stage/step, we need to know the longest wait duration for each stage/step, etc.

### Task Lists (TBD)

- [ ] Sink to MySQL
  - [ ] conflict dependency graph 
  - [ ] x
- [ ] Sink to Cloud Storage
  - [ ] x
  - [ ] x
- [ ] Sink to MQ (Kafka, Pulsar)
  - [ ] x
  - [ ] Simple Protocol
    - [ ] x
