### ISSUE TITLE
Stability (cdc) Improve the stability of TiCDC

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tiflow#10343]
This is a task tracking issue

### Principle of prioritizing TiCDC stability issues

We treat TiCDC stability issues as following priorities
- When this issue happens, the replication/changefeed can be stuck/failed and can't recover by TiCDC itself. We should treat this category as top priority(P1). Because if such issue happens, it means we/users should handle it manually.
- When this issue happens, the replication lag will increase a lot unexpected. This type of issue is not that critical that P1 issues, but will breach the SLO of TiCDC, we treat them as P2 issues.
- Enhancements like reduce resources usage, ... we treat them as P3 issues.

### Tasks Tracking
- [ ] (P1) Resolve TS might be stuck @flowbehappy 
  - [ ] 
- [ ] (P1) Sink might be stuck
  - [ ] https://github.com/pingcap/tiflow/pull/10335 @zhangjinpeng1987 
- [ ] (P2) replication lag increase issues
  - [ ] https://github.com/pingcap/tiflow/issues/10341 @zhangjinpeng1987

**Comment by flowbehappy** [comment]
https://github.com/pingcap/tiflow/issues/10157 @zhangjinpeng1987  resolve ts gets stuck issue
