### ISSUE TITLE
(TiCDC) Tracking issue for implement client authentication

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#10544]
##  Authenticate using a TLS client certificate
- [x] https://github.com/pingcap/tiflow/pull/10084
- [ ] Support configuring certificate authorities for clients

## Authenticate using TiDB Credentials
- [ ] Support for authenticating client access with TiDB username and password
- [ ] Authenticate to CLI using TiDB Credentials
- [ ] Authenticate to API using TiDB Credentials
