### ISSUE TITLE
(TiCDC) Tracking issue for pulsar mtls and oauth integration tests

### ISSUE THREAD

**Issue by sdojjy** [pingcap/tiflow#10653]
- [x] build a docker image with golang, java and pulsar 
-  [x] pulsar consumer support oauth and mtls
- [x] support starting a mtls auth pulsar cluster  in integration test
- [ ] support starting a mtls auth pulsar cluster  in integration test
- [ ] add mtls and oauth integration tests
