### ISSUE TITLE
Tracking issues for improving tests of ticdc

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#10742]
# Flaking unit tests
- [x] https://github.com/pingcap/tiflow/issues/10771
- [x] https://github.com/pingcap/tiflow/issues/10773
- [x] https://github.com/pingcap/tiflow/issues/10756
- [x] https://github.com/pingcap/tiflow/issues/10762
- [x] https://github.com/pingcap/tiflow/issues/10764
- [x] https://github.com/pingcap/tiflow/issues/10769
- [x] https://github.com/pingcap/tiflow/issues/10783
- [x] https://github.com/pingcap/tiflow/issues/10785
- [x] https://github.com/pingcap/tiflow/issues/10787
- [x] https://github.com/pingcap/tiflow/issues/10815

# Flaking integration tests
- [x] #10912

# Doc enhancement
- [x] https://github.com/pingcap/tiflow/pull/10746

**Comment by wk989898** [comment]
see #10746

**Comment by asddongmen** [comment]
All task finished.
