### ISSUE TITLE
Tracking for unstable UT in TiCDC

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tiflow#10763]
This issue is used to keep track of all issues about unstable UT in TiCDC. 

- [x] https://github.com/pingcap/tiflow/issues/10762
- [ ] https://github.com/pingcap/tiflow/issues/10764
- [x] https://github.com/pingcap/tiflow/issues/10769
