### ISSUE TITLE
Tracking issue for flaky tests

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#2246]
**This is a tracking  issue for unstable tests, and each unstable test is linked as a subtask.**

# TiCDC

- [x] https://github.com/pingcap/ticdc/issues/2273
- [ ] https://github.com/pingcap/ticdc/issues/2289
- [x] https://github.com/pingcap/ticdc/issues/2293
- [x] https://github.com/pingcap/ticdc/issues/2296  **Test deprecated**
- [x] https://github.com/pingcap/ticdc/issues/2314
- [x] https://github.com/pingcap/ticdc/issues/2345
- [x] https://github.com/pingcap/ticdc/issues/2346
- [x] https://github.com/pingcap/ticdc/issues/2347
- [x] https://github.com/pingcap/ticdc/issues/2348
- [x] https://github.com/pingcap/ticdc/issues/2349
- [x] https://github.com/pingcap/ticdc/issues/2405 **Test deprecated**
- [x] https://github.com/pingcap/ticdc/issues/2469
- [x] https://github.com/pingcap/ticdc/issues/2500
- [x] https://github.com/pingcap/ticdc/issues/2540
- [x] https://github.com/pingcap/ticdc/issues/2614
- [x] https://github.com/pingcap/ticdc/issues/2624
- [x] https://github.com/pingcap/ticdc/issues/2650
- [x] https://github.com/pingcap/ticdc/issues/2651
- [x] https://github.com/pingcap/ticdc/issues/2653
- [x] https://github.com/pingcap/ticdc/issues/2662
- [ ] https://github.com/pingcap/ticdc/issues/2688
- [x] https://github.com/pingcap/ticdc/issues/2694
- [x] https://github.com/pingcap/ticdc/issues/2731
- [x] https://github.com/pingcap/ticdc/issues/2747
- [ ] https://github.com/pingcap/tiflow/issues/4567
- [x] https://github.com/pingcap/ticdc/issues/2748
- [x] https://github.com/pingcap/ticdc/issues/2792
- [x] https://github.com/pingcap/ticdc/issues/2797
- [x] https://github.com/pingcap/ticdc/issues/2813
- [x] https://github.com/pingcap/ticdc/issues/2958
- [x] https://github.com/pingcap/ticdc/issues/2887
- [x] https://github.com/pingcap/ticdc/issues/2993
- [x] https://github.com/pingcap/ticdc/issues/3041
- [x] https://github.com/pingcap/ticdc/issues/3115
- [x] https://github.com/pingcap/ticdc/issues/3185
- [x] https://github.com/pingcap/ticdc/issues/3207
- [x] https://github.com/pingcap/ticdc/issues/3232
- [x] https://github.com/pingcap/ticdc/issues/3301
- [x] https://github.com/pingcap/ticdc/issues/3302
- [x] https://github.com/pingcap/ticdc/issues/3341
- [x] https://github.com/pingcap/ticdc/issues/3381
- [x] https://github.com/pingcap/ticdc/issues/3399
- [x] https://github.com/pingcap/ticdc/issues/3421
- [x] https://github.com/pingcap/ticdc/issues/3443
- [x] https://github.com/pingcap/ticdc/issues/3626
- [x] https://github.com/pingcap/ticdc/issues/3679
- [x] https://github.com/pingcap/ticdc/issues/3750
- [x] https://github.com/pingcap/ticdc/issues/3805
- [x] https://github.com/pingcap/ticdc/issues/3815 
- [x] https://github.com/pingcap/ticdc/issues/3825
- [x] https://github.com/pingcap/ticdc/issues/3850
- [x] https://github.com/pingcap/ticdc/issues/3945
- [x] https://github.com/pingcap/tiflow/issues/3963
- [x] https://github.com/pingcap/tiflow/issues/3989
- [x] https://github.com/pingcap/tiflow/issues/4135
- [x] https://github.com/pingcap/tiflow/issues/4139
- [x] https://github.com/pingcap/tiflow/issues/4319
- [x] https://github.com/pingcap/tiflow/issues/4320
- [x] https://github.com/pingcap/tiflow/issues/4416
- [x] https://github.com/pingcap/tiflow/issues/4447
- [x] https://github.com/pingcap/tiflow/issues/4461
- [x] https://github.com/pingcap/tiflow/issues/4473
- [x] https://github.com/pingcap/tiflow/issues/4480
- [x] https://github.com/pingcap/tiflow/issues/4549
- [x] https://github.com/pingcap/tiflow/issues/4586
- [x] https://github.com/pingcap/tiflow/issues/4600
- [x] https://github.com/pingcap/tiflow/issues/4731
- [x] https://github.com/pingcap/tiflow/issues/4765
- [x] https://github.com/pingcap/tiflow/issues/4785
- [x] https://github.com/pingcap/tiflow/issues/3180
- [ ] https://github.com/pingcap/tiflow/issues/4856
- [x] https://github.com/pingcap/tiflow/issues/4895
- [x] https://github.com/pingcap/tiflow/issues/4939
- [x] https://github.com/pingcap/tiflow/issues/4958
- [x] https://github.com/pingcap/tiflow/issues/4975
- [ ] https://github.com/pingcap/tiflow/issues/4961
- [x] https://github.com/pingcap/tiflow/issues/4941
- [x] https://github.com/pingcap/tiflow/issues/5064
- [x] https://github.com/pingcap/tiflow/issues/5076
- [x] https://github.com/pingcap/tiflow/issues/5083
- [x] https://github.com/pingcap/tiflow/issues/5084
- [x] https://github.com/pingcap/tiflow/issues/5090
- [x] https://github.com/pingcap/tiflow/issues/5210
- [x] https://github.com/pingcap/tiflow/issues/5356
- [x] https://github.com/pingcap/tiflow/issues/5406
- [x] https://github.com/pingcap/tiflow/issues/5107
- [ ] https://github.com/pingcap/tiflow/issues/5445
- [x] https://github.com/pingcap/tiflow/issues/5736
- [x] https://github.com/pingcap/tiflow/issues/5792
- [x] https://github.com/pingcap/tiflow/issues/5798
- [x] https://github.com/pingcap/tiflow/issues/6046
- [x] https://github.com/pingcap/tiflow/issues/6167
- [x] https://github.com/pingcap/tiflow/issues/6804
- [x] https://github.com/pingcap/tiflow/issues/6895
- [x] https://github.com/pingcap/tiflow/issues/7201

----------------------------------------------------

# DM

If you encounter the unstable test repeatedly, you can add `+n` in the end of following test. For example, 

> - [ ] https://github.com/pingcap/ticdc/issues/3283 +1, +4, ...

We will give priority to frequent unstable tests.

- [x] https://github.com/pingcap/ticdc/issues/3283
- [x] https://github.com/pingcap/ticdc/issues/3254
- [ ] https://github.com/pingcap/ticdc/issues/3328
- [x] https://github.com/pingcap/ticdc/issues/3335
- [ ] https://github.com/pingcap/ticdc/issues/3336
- [ ] https://github.com/pingcap/ticdc/issues/3353
- [x] https://github.com/pingcap/ticdc/issues/3380
- [x] https://github.com/pingcap/ticdc/issues/3394
- [x] https://github.com/pingcap/ticdc/issues/3398
- [x] https://github.com/pingcap/ticdc/issues/3400
- [x] https://github.com/pingcap/ticdc/issues/3401
- [ ] https://github.com/pingcap/ticdc/issues/3404
- [x] https://github.com/pingcap/ticdc/issues/3407
- [x] https://github.com/pingcap/ticdc/issues/3409
- [x] https://github.com/pingcap/ticdc/issues/3450
- [x] https://github.com/pingcap/ticdc/issues/3495
- [ ] https://github.com/pingcap/tiflow/issues3518
- [ ] https://github.com/pingcap/ticdc/issues/3657
- [ ] https://github.com/pingcap/ticdc/issues/3728
- [ ] https://github.com/pingcap/ticdc/issues/3777
- [ ] https://github.com/pingcap/ticdc/issues/3785
- [x] https://github.com/pingcap/ticdc/issues/3791
- [ ] https://github.com/pingcap/ticdc/issues/3913
- [ ] https://github.com/pingcap/ticdc/issues/3915
- [x] https://github.com/pingcap/tiflow/issues/4029
- [x] https://github.com/pingcap/tiflow/issues/4131
- [x] https://github.com/pingcap/tiflow/issues/4132
- [x] https://github.com/pingcap/tiflow/issues/4134
- [x] https://github.com/pingcap/tiflow/issues/4158
- [ ] https://github.com/pingcap/tiflow/issues/4168
- [x] https://github.com/pingcap/tiflow/issues/4171
- [x] https://github.com/pingcap/tiflow/issues/4174
- [x] https://github.com/pingcap/tiflow/issues/4243
- [x] https://github.com/pingcap/tiflow/issues/4246
- [x] https://github.com/pingcap/tiflow/issues/4255
- [x] https://github.com/pingcap/tiflow/issues/4312
- [x] https://github.com/pingcap/tiflow/issues/4554
- [x] https://github.com/pingcap/tiflow/issues/4565
- [ ] https://github.com/pingcap/tiflow/issues/4875 
- [x] https://github.com/pingcap/tiflow/issues/5089
- [x] https://github.com/pingcap/tiflow/issues/5235
- [ ] https://github.com/pingcap/tiflow/issues/5488
- [x] https://github.com/pingcap/tiflow/issues/5489
- [ ] https://github.com/pingcap/tiflow/issues/5490
- [x] #5729 
- [x] #5730 
- [x] #5731 
- [ ] #5732 
- [x] #5733 
- [x] https://github.com/pingcap/tiflow/issues/7569
----------------------------------------------------

# Engine
- [x] https://github.com/pingcap/tiflow/issues/5515
- [x] https://github.com/pingcap/tiflow/issues/5699
- [x] https://github.com/pingcap/tiflow/issues/7168

**Comment by hi-rustin** [comment]
Basic guidelines for fixing these tests.
1. discover unstable tests.
2. Create a corresponding issue to track the unstable tests.
3. Submit a PR to temporarily skip the unstable test. (The expected time to fix must be set in the PR)
4. start fixing the unstable tests.
5. Bring the test back online.

First, our integration tests need to support skipping some unstable tests, and I will adapt the sh script to support this mechanism.

**Comment by asddongmen** [comment]
Great works! I will close it since it is stale.

**Comment by MimeLyc** [comment]
update
