### ISSUE TITLE
Tracking issue for merging dm and ticdc repos

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#3194]
- [x] How to cherry-pick the specific commit<COMMIT_SHA> to DM repo See: https://github.com/pingcap/ticdc/issues/3194#issuecomment-954837205
- [x] Github Actions:  https://github.com/pingcap/ticdc/issues/3173
- [ ] Merge the dm and cdc code into the root directory to make it conform to the go project standard structure ref: https://github.com/pingcap/ticdc/issues/2199
- [x] https://github.com/pingcap/ticdc/issues/3175
- [x] #3195
- [x] Refine `required` field in CI test. ref: https://github.com/ti-community-infra/configs/pull/453
- [x] Refine CI trigger command, @hi-rustin  will adjust it.
    - [x] #3196
- [ ] Reuse codes
    - [ ] https://github.com/pingcap/ticdc/issues/3242

**Comment by gozssky** [comment]
We also need to integrate the DM code structure into the root project structure, rather than always as a sub directory.

**Comment by hi-rustin** [comment]
> We also need to integrate the DM code structure into the root project structure, rather than always as a sub directory.

Having adjusted the third TODO item description, we do need to work towards a standard structure!

**Comment by Ehco1996** [comment]
how about merge `dm/pkg/xx` to `pkg/xx` ?

**Comment by lonng** [comment]
> how about merge `dm/pkg/xx` to `pkg/xx` ?

Make sense
