### ISSUE TITLE
Tracking issue for LevelDB sorter

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#3227]
This issue tracks leveldb sorter development, a new sorter, it utilizes leveldb to store and sort replication data. It is designed to handle many table replication scenario by limting total resources consumption, e.g., files in disk and open FD.

The preview PR: https://github.com/pingcap/ticdc/pull/3201

The above PR will be divided into several PRs to speed up merging process.

- [x] #3029 
- [x] #3095 
- [x] #3154 
- [x] https://github.com/pingcap/ticdc/pull/3272
- [x] https://github.com/pingcap/ticdc/pull/3202 add leveldb actor, it reads, writes and deletes key value pair in its leveldb.
- [x] https://github.com/pingcap/ticdc/issues/3364 refactor sorter to sink flow control, flow controlled by row size.
- [x] https://github.com/pingcap/ticdc/pull/3279, it cleans up data that belongs to removed tables.
- [x] https://github.com/pingcap/ticdc/pull/3406, it manages lifecyclic of leveldb actor and clean actor.
- [x] https://github.com/pingcap/ticdc/pull/3610, abstract goleveldb APIs.
- [x] https://github.com/pingcap/ticdc/pull/3492, add table sorter, it receives table data from puller and sends resolved data to sink.
- [x] https://github.com/pingcap/ticdc/pull/3201, so it can be used.
- [x] https://github.com/pingcap/ticdc/pull/3837 to GC deleted kv entires and reclaim disk space.
- [x] https://github.com/pingcap/tiflow/pull/4147
- [x] https://github.com/pingcap/tiflow/pull/4148
- [x] #4631 
- [x] #4832 

|   |   |
| - | - |
| <img src="https://user-images.githubusercontent.com/2150711/139533157-1b5cc402-8133-4e0d-b35d-fde17114da6e.png"  width="500"/> | <img src="https://user-images.githubusercontent.com/2150711/139680638-60907f1d-2339-40a2-bf2d-d262b619d70e.png"  width="300"/>|
