### ISSUE TITLE
Tracking issue for potential deadlocks

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#3338]
This issue tracks potential deadlocks of TiKV to TiCDC replication data flow.

The list below are known issues,

1. TiKV CDC -> TiKV gRPC : rust (bounded+unbounded) channel + memory quota
   * a. EventFeed may meltdown due to exceed memory quota, it could cause livelock.

2. TiKV gRPC -> TiCDC gRPC clients : gRPC flow control，see [HTTP2 RFC][1].
    * a. One connection may contain multiple EventFeed RPCs.
    * b. **One slow EventFeed RPC may block entire connection, head-of-line blocking.**
    * c. **In TiCDC, all EventFeed RPCs run on a set of shared gRPC Clients, EventFeed for table data and DDL metadata may interfere.**

3. TiCDC gRPC Client -> TiCDC KV Client : golang channel
    * a. **In TiCDC, ChangeData events are processed by a set of shared region workers. One slow (hotspot) region may block other regions.**

4. TiCDC KV Client -> Table Pipeline : golang channel
    * a. Puller -> Sorter : golang channel. **Sorter.AddEntry is a blocking API, blocking duration is related to disk IO.**
    * b. Sorter -> Mounter : golang channel. **Decoding ChangeData events may be blocked mounter.schemaStorage.GetSnapshot. GetSnapshot reads table schema, it waits DDL puller resolved-ts.**
    * c. Sorter -> Sink : golang channel, no known issue.
    * d. Sink -> MySQL/Kafka, no known issue.

[1]: https://datatracker.ietf.org/doc/html/rfc7540#section-5.2

Solutions for above issues:

- [x] 1. For 1.a, no simple solution, it can be fixed only when refactor the "push" model to "pull" model.
- [x] 2. For 2.a and 2.b, no simple solution, but the risk is low as long as TiCDC receives fast enough.
- [ ] 3. For 2.c and 4.b, they are strongly related, and can cause deadlock, we should:
  - a. DDL EventFeeds should run on a dedicate gRPC connection, must not mix with table data.
- [x] 4. For 3.a, similar to 2.c, it may cause deadlock, we should:
  - a. DDL EventFeed should run on a dedicate KV Client and region workers, must not mix with table data.
- [ ] 5. For 4.a, `Sorter.AddEntry` should refactor into nonblocking API.
- [ ] 6. For 4.b, progress of table data and DDL metadata varies, decoding table data may waits DDL metadata, we should:
  - a. Limit sorter output by only outputting events whose commit ts is less or equal to DDL resolved ts.
