### ISSUE TITLE
DDL max retry logic cause detail error info lose  or  missing error state

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#3361]
### What did you do?

1. Create upstream tidb and downstream mysql
2. Create a related changfeed in ticdc
3. Drop table in upstream and then recover table
4. query changefeed status

### What did you expect to see?

changfeed status show error and the detail error

### What did you see instead?

```
{
 "state": "normal",
 "tso": 429002325861335041,
 "checkpoint": "2021-11-10 11:13:19.410",
 "error": {
  "addr": "127.0.0.1:41010",
  "code": "CDC:ErrOwnerUnknown",
  "message": "[CDC:ErrReachMaxTry]reach maximum try: 20"
 }
}
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.3.0-alpha-1304-ga96deab-dirty
```

TiCDC version (execute `cdc version`):

```console
v5.2.1
```

### TODO

- [ ]  Add detail error info In MaxRetryError
- [ ]  Fix the changefeed resume logic which will occur frequently

**Comment by maxshuang** [comment]
After another test under the same circumstance,  I found this ddl  error could be missed  and the changfeed state is always normal.

**Comment by maxshuang** [comment]
Update issue status：
I get from the ticdc log that this error will cause the close and restart of changefeed with the 200ms interval, which is meaningless for user to observe the error

**Comment by maxshuang** [comment]
Track 2 TODO list need to improve:

- [ ] Add detail error info In MaxRetryError
- [ ] Fix the changefeed resume logic which will occur frequently

**Comment by asddongmen** [comment]
> Update issue status： I get from the ticdc log that this error will cause the close and restart of changefeed with the 200ms interval, which is meaningless for user to observe the error

Is this frequent retry also unreasonable? Because each retry needs to acquire and release resources, this will cause a huge waste of resources.
