### ISSUE TITLE
[Tracking] use lightning as DM's load unit implementation

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#3510]
### Is your feature request related to a problem?

to provide better performance, and to deprecate the old loader code

### Describe the feature you'd like

- [x] https://github.com/pingcap/ticdc/issues/3509
- [x] https://github.com/pingcap/ticdc/issues/3482
- [x] https://github.com/pingcap/ticdc/issues/3519
- [x] https://github.com/pingcap/ticdc/issues/3511
- [x] https://github.com/pingcap/tiflow/issues/5505
- [x] https://github.com/pingcap/ticdc/issues/3339
- [x] https://github.com/pingcap/tiflow/issues/5867
- [x] https://github.com/pingcap/tiflow/issues/7068

**Comment by sunzhaoyang** [comment]
Regarding the new backend configuration item, I hope it could be optimized.

```
tidb:
  backend: "tidb"
```

1. location
Since this configuration is related to target, I think it can be placed in

```
target-database:
  host: "127.0.0.1"
  port: 4400
  user: "root"
  password: ""
  security:
    ssl-ca: "dir-placeholer/task-ca.pem"
    ssl-cert: "dir-placeholer/dm.pem"
    ssl-key: "dir-placeholer/dm.key"
  import-mode: "${value}"  # If multiple downstreams (N->N) are to be added in the future, this approach can also continue to be used
```

2. the value of the configuration item is not easy to understand, for historical reasons Lightning called tidb and local two modes. We can improve it in dm so that new users can understand it better

- `tidb/local` could be replaced with `logical/physical` or `sql/sst`？,looks better to understand

@lance6716
