### ISSUE TITLE
Tracking issue for DM WebUI

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/tiflow#3583]
**This is a tracking issue for develop of DM WebUI, both for UI and OpenAPI**

# UI

* https://github.com/pingcap/ticdc/pull/3449
* [x] delete dm-portal code https://github.com/pingcap/tiflow/pull/4247
* [x] any request to webui should  redirect to dashboards.html https://github.com/pingcap/tiflow/pull/4350

# OpenAPI

- [x] open openapi as default config https://github.com/pingcap/ticdc/pull/3836
- [x] support task status in List API https://github.com/pingcap/tiflow/pull/3971
- [ ] ~~add more config in task https://github.com/pingcap/ticdc/issues/3397~~
- [x] https://github.com/pingcap/ticdc/pull/3600
- [x] support task config template
    - [x] https://github.com/pingcap/ticdc/pull/3620
    - [x] https://github.com/pingcap/ticdc/pull/3656
    - [x] dmctl get-config support operate template config
- [x] ~~export source/task config in v1/v2 format~~
- [x] ~~dmctl support convert task/source config in OpenAPI json Format to v1 yaml config~~
- [ ] https://github.com/pingcap/docs-cn/pull/8612
- [x] task status support error msg https://github.com/pingcap/tiflow/pull/4421
