### ISSUE TITLE
[TiCDC] Enable new scheduler (p2p) on master branch

### ISSUE THREAD

**Issue by liuzix** [pingcap/tiflow#4126]
Remaining work to be done for enabling p2p on master branch

P1 items (before branching out release-5.4) :
- [x] Fix move_table test case #4120 
- [x] Add Grafana panels #4108 
- [x] Fix some `cdc cli` commands #3931 
- [x] Add a user-configurable switch to turn on p2p #4151 

P2 items:
- [ ] Refine logging (PR pending).
- [ ] Unit case improvements for existing packages (owner and processor) (PR pending)
- [ ] Enables p2p by default on master branch.

**Comment by overvenus** [comment]
It has been enabled since v6.0.0.
