### ISSUE TITLE
Tracking issue for enhance kafka test

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#4425]
* [ ] inject random cdc -> kafka network loss chaos 
* [ ] inject kafka -> cdc owner network loss chaos
* [ ] inject kafka -> random cdc node network loss chaos
* [ ] inject kafka broker process random failed chaos
