### ISSUE TITLE
tracking issue for delete dm-ansible

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/tiflow#4654]
dm-ansible is no longer maintained, the default install tool is  `tiup`

so the corresponding code should be removed

---

- [x] move dashboard.json out of dm-ansible dir https://github.com/pingcap/tiflow/pull/4726,https://github.com/pingcap/tiflow/pull/4791
- [x] adapt release CI
- [ ] delete dm-ansible and monitoring dir https://github.com/pingcap/tiflow/pull/4917
