### ISSUE TITLE
Tracking issues for migrating TiDB DDL/DML related test

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#4674]
## Background
In order to ensure the correctness of TiCDC DDL/DML-related processing logic and to facilitate the verification of the correctness of pr modification, it is necessary to introduce DDL/DML-related feature test cases in TIDB.

## Test Form

- Integration Test
- Test-infra

### Integration Test https://github.com/pingcap/tidb-test

- [ ]   [ddl_test](https://github.com/pingcap/tidb-test/tree/master/ddl_test)  --- multi-types DDL
- [ ]   [mysql_test](https://github.com/pingcap/tidb-test/tree/master/mysql_test)  --- mysql test cases
    - [ ] [alter_table.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/alter_table.test)/[alter_table1.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/alter_table1.test)/[alter_table_pk.test ](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/alter_table_PK.test) --- alter table related ddl
    - [ ]     [auto_increment.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/auto_increment.test)  --- auto-increment related
    - [ ]    [bigint.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/bigint.test) --- bigint type related
    - [ ]    [composite_index.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/composite_index.test) --- multi-index related
    - [ ]    [concurrent_ddl.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/concurrent_ddl.test) --- concurrent DDL related
    - [ ]    [ctype_gbk.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/ctype_gbk.test) --- gbk charset related
    - [ ]    [date_*.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/date_formats.test)[ ](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/date_time_ddl.test) -- datetime related
    - [ ]    [delete.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/delete.test) ---  delete DML
    - [ ]     [drop.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/drop.test) --- drop DDL
    - [ ]     [expression_index.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/expression_index.test) ---expression index
    - [ ]     [field_length.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/field_length.test) 
    - [ ]     [gcol_alter_table.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/gcol_alter_table.test)  ---generate column
    - [ ]     [insert_*.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/insert.test) --- insert DML
    - [ ]     [issue_*.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/issue_11208.test) --- issues related
    - [ ]     [json.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/json.test)/[json_functions.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/json_functions.test)/[json_gcol.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/json_gcol.test) --- json type related
    - [ ]     [multi_update.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/multi_update.test) --- update multi-tables in one sql
    - [ ]     [mysql_replace.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/mysql_replace.test) --- replace
    - [ ]     [partition_*.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/partition_hash.test) --- partition related
    - [ ]     [replace.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/replace.test) --- replace into
    - [ ]     [single_delete_update.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/single_delete_update.test)
    - [ ]     [str_quoted.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/str_quoted.test) --- string with quota
    - [ ]     [temp_table.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/temp_table.test) 
    - [ ]     [time.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/time.test)/[timestamp_insert.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/timestamp_insert.test)/[timestamp_update.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/timestamp_update.test) --- timestamp related
    - [ ]     [transaction_isolation_func.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/transaction_isolation_func.test) --- isolation related
    - [ ]     [type*.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/type.test)  --- data type binary/decimal/enum/time/timestamp/uint/varchar 
    - [ ]     [update.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/update.test)/[update_stmt.test](https://github.com/pingcap/tidb-test/blob/master/mysql_test/t/update_stmt.test)  --- tidb bug related
- [ ]   [randgen-test](https://github.com/pingcap/tidb-test/tree/master/randgen-test)  --- go-randgen data test
- [ ]   [tidb_test](https://github.com/pingcap/tidb-test/tree/master/tidb_test)  --- DDL/DML related
- [ ]   [massive_ddl_test](https://github.com/pingcap/tidb-test/tree/master/massive_ddl_test) --- massive DDL 
- [ ]   https://github.com/PingCAP-QE/schrddl  --- DDL related
### Test-infra 
- [ ]   [TODO]

### What did you see instead?

*

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```
