### ISSUE TITLE
Tracking issue for dm to supports one worker bound to several sources

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tiflow#4687]
### Is your feature request related to a problem?

1. We need to start the number of upstream sources dm-workers to replicate data now, which is too hard to maintain for users.
2. If we want to support subtask level arrangements, we must implement worker bound to several sources first.

### Describe the feature you'd like

Make supports one worker bound to several sources. We need to implement the following subtasks:
- dm-master section
    - [ ] rewriting etcd keys to new format to support multi-sources for worker
    - [ ] rolling upgrade adaptations
    - [ ] scheduler modification to adapt to multiple sources

- dm-worker section
    - [ ] relay, subtask loader part directory adaptation
    - [ ] server supports up several internal sourceWorkers and changing map to support multiple sources
    - [ ] worker etcd watch logic adaptations

- rebalancing algorithm drvyion
    - [ ] abstract scheduling interface
    - [ ] support source number balancing algorithm

    - add user interface
        - [ ] Support setting balancing algorithm
        - [ ] Support manual scheduling by weight

Translated with www.DeepL.com/Translator (free version)
