### ISSUE TITLE
Tracking issue for codec interface type assertion failed

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#4737]
### What did you do?

When creating a changefeed with Kafka sink, the codec will be used to encode `RowChangedEvent` into a message. At the moment, TiCDC support several different codec protocols, we should make sure all protocol can handle the content of `RowChangedEvent` correctly, especially the `Column.Value` field, which is an interface.

### What did you expect to see?

All protocols can handle `Column.Value` field correctly, but some failed.

### What did you see instead?

The server panic.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

Most recent bug report happened in `v5.4.0`, but we should check all release branches.

### Canal-JSON / Canal

* [x] https://github.com/pingcap/tiflow/issues/4635
* [x] https://github.com/pingcap/tiflow/issues/4736

### Open protocol

* [x] https://github.com/pingcap/tiflow/issues/2758

### test
* [x] #4787
