### ISSUE TITLE
[tracking] Better support MariaDB/new MySQL features for upstream

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#5141]
### Is your feature request related to a problem? Please describe

currently DM can't support

MariaDB
- [ ] (*) unsupport type 140 https://github.com/pingcap/tiflow/issues/10158
- [ ] (*) log_bin_compress=1 https://github.com/pingcap/tiflow/issues/10159
- [ ] (*) MariadbBinLogCheckPointEvent https://github.com/pingcap/tiflow/issues/4326
- [ ] (10.5.11) BINLOG MONITOR privilege https://github.com/pingcap/tiflow/issues/10160
- [ ] (10.2), https://github.com/pingcap/tiflow/issues/5133

### Describe the feature you'd like

implement them

**Comment by lance6716** [comment]
We can use issue label "MariaDB' to find related issues. Closing this issue.

https://github.com/pingcap/tiflow/labels/MariaDB
