### ISSUE TITLE
Tracking issue for splitting big transaction

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#5231]
### Before asking a question, make sure you have

- [X] Searched existing Stack Overflow questions
- [X] Googled your question
- [X] Searched open and closed [GitHub issues](https://github.com/pingcap/tiflow/issues?q=is%3Aissue)
- [X] Read the [documentation](https://docs.pingcap.com/tidb/stable)

### What is your question?

Tracking issue for splitting big transaction
