### ISSUE TITLE
Tracking issue for Sink Module Refactoring

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#5283]
This is a tracking issue for Sink Module Refactoring.
- [x] [remove useless buffers](https://github.com/pingcap/tiflow/pull/5284)
- [x] [remove useless buffer sink](https://github.com/pingcap/tiflow/pull/5302)
- [x] https://github.com/pingcap/tiflow/issues/5425
- [x] https://github.com/pingcap/tiflow/pull/5461
