### ISSUE TITLE
Tracking issue for implementing DM into engine

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiflow#5504]
# This issue track the progress of DM
- [ ] precheck
  - [x] task cfg adjust
  - [ ] source cfg adjust
  - [ ] database adjust
  - [x] checker
- [ ] shard ddl
- [ ] command
  - [ ] binlog
  - [ ] binlog-schema
  - [ ] config
  - [ ] relay
  - [ ] operate-task
  - [ ] query-status
    - [x] task-status
    - [ ] source-status
  - [ ] shard-ddl-lock
  - [ ] validation
- [ ] metrics
- [ ] openapi
- [ ] upgrade
- [ ] error code
- [ ] log
- [ ] test 
- [ ] Unified metadata/config format（yaml/toml/json)

**Comment by lance6716** [comment]
"error code" development will be postponed until Web UI has decided the error format.
