### ISSUE TITLE
engine: Tracking issue for merge file resource GC

### ISSUE THREAD

**Issue by liuzix** [pingcap/tiflow#5513]
- [x] Preparation #5514 
- [x] Core GC logic #5557 
- [x] Adjust JobManager #5559 
- [x] Adjust ExecutorManager #5565
- [x] Implement `Discard` and `OnWorkerClosed` #5623 
- [x] Integrate all parts 1) #5596 2) #5646
