### ISSUE TITLE
Continues standardize of project

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#5687]
### Is your feature request related to a problem?

The tiflow repo evolves from a monomeric TiCDC repo, to a combination of DM, TiCDC and Dataflow Engine, the evolution history is as follows
- https://github.com/pingcap/tiflow/issues/3194
- https://github.com/pingcap/tiflow/issues/5352

Although the migration tasks have finished, but we still have more works to do, including not limited to unify code style, standardize code structure, etc. This issue lists all kinds of such work.

### Describe the feature you'd like

- [ ] Standardize code structure, ref: https://github.com/pingcap/tiflow/issues/2199, sub tasks include
  - [ ] Move the core code of TiCDC into an independent ticdc dir.
  - [ ] Move all public libraries into the `github.com/pingcap/tiflow/pkg` package.
- [ ] Code style
  - [x] Unify import group.
- [ ] Engineering implementation
  - [ ] replace `github.com/pingcap/check` with `github.com/stretchr/testify` in DM. TiCDC has finished this task, ref: https://github.com/pingcap/tiflow/issues/2164
- [ ] Document related
  - [x] refine readme badges. #5878
