### ISSUE TITLE
Tracking issue for implementing OpenAPI for engine

### ISSUE THREAD

**Issue by gozssky** [pingcap/tiflow#5689]
## Development Task

There is a prototype implementation in https://github.com/pingcap/tiflow/pull/5563.

- [x] HTTP handler  registration in executor https://github.com/pingcap/tiflow/pull/5696
- [x] OpenAPI framework in servermaster https://github.com/pingcap/tiflow/pull/5713
- [x] OpenAPI forwarding from servermaster to executor https://github.com/pingcap/tiflow/pull/5713
- [x] OpenAPI implementation for servermaster https://github.com/pingcap/tiflow/pull/6669
