### ISSUE TITLE
Tracking issue for Optimize DM task lifecycle management and dmctl commands

### ISSUE THREAD

**Issue by WizardXiao** [pingcap/tiflow#5898]
### Is your feature request related to a problem?

**This is a tracking issue for Optimize task lifecycle management and all command formats of dmctl.**

# Optimize commands
- [ ] Optimize task commands
- [ ] Optimize source commands
- [ ] Optimize relay commands
- [ ] Optimize ddl-lock commands
- [ ] Optimize member commands

### Describe the feature you'd like

a

**Comment by GMHDBJD** [comment]
If any interface is changed, please notify me or change it for engine also...

**Comment by WizardXiao** [comment]
> 

ok
