### ISSUE TITLE
Tracking issue for refactoring redo module

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#5920]
### Is your feature request related to a problem?
The current implementation of the `Redo` module flushes S3 too frequently, which may trigger some cloud infrastructure restrictions. 

### Describe the feature you'd like
Refactor `Redo` module to reduce flush frequency and improve the stability of the module.

### Related Issues
- [x] remove useless interface and enable leak test
- [ ] manager resolvedTs in `redoManager`
- [x] https://github.com/pingcap/tiflow/issues/6011
- [ ] https://github.com/pingcap/tiflow/issues/5924
- [x] https://github.com/pingcap/tiflow/issues/5942
- [ ] https://github.com/pingcap/tiflow/issues/6051

### Other tasks
- [ ] [Optimize the monitoring structure of the redo module](https://github.com/pingcap/tiflow/pull/5683#discussion_r911179347)
- [ ] [Adjust flush parameters based on test results](https://github.com/pingcap/tiflow/pull/5683#discussion_r911243576)
