### ISSUE TITLE
Tracking issue for refactor sink

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#5928]
Implement MQ sink and MySQL sink in asynchronous mode to improve the throughput of the sink and reduce the coupling of modules.

- https://github.com/pingcap/tiflow/pull/7214
- [Add MQ worker batch flush duration](https://github.com/pingcap/tiflow/pull/7263)
- Add flushed rows dashboards in the dataflow row
- Add more metrics for progress tracking
- Add table sink wrapper and table progress heap https://github.com/pingcap/tiflow/pull/7453

**Comment by hi-rustin** [comment]
Enable pull-based sink preparations:
1. [ ] Fix all panic issue
2. [ ] Solve the no-data table advance issue
3. [ ] Add sorter stats info
4. [ ] Handle err from `sinkMnager.GetTableStats`
5. [ ] Use SourceManger in SinkMnager instead of SortEngine and move mounted iter into source manager
6. [ ] Add test for pullerWrapper and SourceManger
7. [ ] Add test for redo log worker
8. [ ] Add test for generating redo task function
