### ISSUE TITLE
engine package related enhancement

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#6022]
### Is your feature request related to a problem?

Some package names and layouts can be optimized.

### Describe the feature you'd like

- [ ] Move engine binary to root path of cmd, rename to `tiflow` command, and makes `df-master` and `df-executor` as subcommand of `tiflow`. ~The command will be either `tiflow master` or `tiflow engine master`~. The command will be `tiflow master`, `tiflow executor` and `tiflow cli`.
  - [x] 1. Move df-executor, df-master to tiflow executor and tiflow master #6111
  - [ ] 2. refactor server master config and executor config
  - [ ] 3. add more unit tests
  - [x] 4. migrate df-master-client to tiflow cli #6181
  - [x] 5. rename other binaries with `df` prefix #6200
- [x] Rename utilities library to singular form, such as renaming `github.com/pingcap/tiflow/engine/etcdutils` to `github.com/pingcap/tiflow/engine/etcdutil` #6030
