### ISSUE TITLE
ticdc redo apply shouldn't depend on meta

### ISSUE THREAD

**Issue by hicqu** [pingcap/tiflow#6189]
### Before asking a question, make sure you have

- [X] Searched existing Stack Overflow questions
- [X] Googled your question
- [X] Searched open and closed [GitHub issues](https://github.com/pingcap/tiflow/issues?q=is%3Aissue)
- [X] Read the [documentation](https://docs.pingcap.com/tidb/stable)

### What is your question?

In the current implement, when applying redo log on a given downstream sink, the event timestamp range is specified from `(meta.checkpointTs, meta.resolvedTs]`.

redo-log meta file is flushed periodically. However, events can be flushed into downstream sinks after **log file** is flushed instead of **redo-log meta**. It makes `cdc redo apply` not be able to ensure downstream integration. For example:

1. cdc table redo log is flushed with timestamp `ts1`;
2. however the current redo-meta resolved timestamp is `ts0`, which is less than `ts1`;
3. events before `ts1` have been flushed into downstream sinks;
4. cdc is killed and `cdc redo apply` is called with the current redo-meta.
5. after recovered, the downstream can contain events after the point `ts0`, which breaks the required integration.

I have prepared a [branch](https://github.com/hicqu/ticdc/tree/6.1.0-for-oncall-5117), and please notice the [fatal log](https://github.com/hicqu/ticdc/blob/6.1.0-for-oncall-5117/cdc/sink/mysql/mysql.go#L236). And the panic really happens when I run the branch:
```
[2022/07/05 16:00:27.117 +08:00] [FATAL] [mysql.go:237] ["[QP] mysqlSink.FlushRowChangedEvents is called with ts less than LogWriterResolved"] [stack="github.com/pingcap/tiflow/cdc/sink/mysql.(*mysqlSink).FlushRowChangedEvents\n\tgithub.com/pingcap/tiflow/cdc/sink/mysql/mysql.go:237\ngithub.com/pingcap/tiflow/cdc/sink.(*tableSink).flushResolvedTs\n\tgithub.com/pingcap/tiflow/cdc/sink/table_sink.go:109\ngithub.com/pingcap/tiflow/cdc/sink.(*tableSink).FlushRowChangedEvents\n\tgithub.com/pingcap/tiflow/cdc/sink/table_sink.go:86\ngithub.com/pingcap/tiflow/cdc/processor/pipeline.(*sinkNode).flushSink\n\tgithub.com/pingcap/tiflow/cdc/processor/pipeline/sink.go:155\ngithub.com/pingcap/tiflow/cdc/processor/pipeline.(*sinkNode).updateBarrierTs\n\tgithub.com/pingcap/tiflow/cdc/processor/pipeline/sink.go:338\ngithub.com/pingcap/tiflow/cdc/processor/pipeline.(*sinkNode).HandleMessage\n\tgithub.com/pingcap/tiflow/cdc/processor/pipeline/sink.go:329\ngithub.com/pingcap/tiflow/cdc/processor/pipeline.(*sinkNode).Receive\n\tgithub.com/pingcap/tiflow/cdc/processor/pipeline/sink.go:289\ngithub.com/pingcap/tiflow/pkg/pipeline.(*nodeRunner).run\n\tgithub.com/pingcap/tiflow/pkg/pipeline/runner.go:65\ngithub.com/pingcap/tiflow/pkg/pipeline.(*Pipeline).driveRunner\n\tgithub.com/pingcap/tiflow/pkg/pipeline/pipeline.go:97"]
``` 

The test shows that the above guess is correct.

To resolve the critical bug, we can consider to 
* always flush log meta when flushing log files, or
* remove log meta from the design, and put `checkpointTs` and `resolvedTs` into redo-log entry

**Comment by amyangfei** [comment]
The timing should be 
flush redo log meta -> update global resolved ts -> flush row changes to backend sink according to global resolved ts

Which rule above is broken?

**Comment by zhaoxinyu** [comment]
/remove-may-affects-4.0

**Comment by nongfushanquan** [comment]
after pr 6207,  issue 6277 will track the new problem on this situation.
