### ISSUE TITLE
Tracking issue for adding integration tests to dataflow engine

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#6255]
- [x] Infrastructure development in https://github.com/PingCAP-QE/ci
- [x] Optimize directories and documents to reduce the difficulty of deploy DFE locally
- [x] Develop integration test framework and some utils
- [x] https://github.com/pingcap/tiflow/issues/6776
- [x] https://github.com/pingcap/tiflow/issues/6554
- [x] https://github.com/pingcap/tiflow/pull/6672

**Comment by maxshuang** [comment]
Close this issue.
Leave the https://github.com/pingcap/tiflow/issues/6776 to track transfer progress.
