### ISSUE TITLE
cdc redo meta can be broken if cdc fails when executing DDLs

### ISSUE THREAD

**Issue by hicqu** [pingcap/tiflow#6277]
### Before asking a question, make sure you have

- [X] Searched existing Stack Overflow questions
- [X] Googled your question
- [X] Searched open and closed [GitHub issues](https://github.com/pingcap/tiflow/issues?q=is%3Aissue)
- [X] Read the [documentation](https://docs.pingcap.com/tidb/stable)

### What is your question?

This bug is introduced with https://github.com/pingcap/tiflow/pull/6207.

Here is a time line example which can meet the bug:
1. for a given cdc instance replicating table A, `A.resolvedTimestamp` = 10;
2. a DDL with timestamp 11 is in executing;
3. no more row events with timestamp higher than 11 can be flushed, but resolved timestamp of table A can still be advanced to 20;
4. shutdown the cdc instance, and run `cdc redo apply` for it;
5. `cdc redo apply` will get `resolved timestamp = 20` from the redo meta, which is wrong.
