### ISSUE TITLE
Add more TiCDC usage documents

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#637]
## Feature Request

**Describe the feature you'd like:**

- [x] 1. Add document about monitor metrics and alert items @overvenus  P0
- [ ] 2. Add document about manual scheduling and scale-up procedure
- [x] 3. Add document about table filter and changefeed config. Should pay attention to **compatibility issue** @overvenus https://github.com/pingcap/docs-cn/pull/3745
- [ ] 4. Add document about `use TiCDC step by step` P0
     - [ ] 4.1. Simple incremental replication case
     - [ ] 4.2. Full data export, import and then incremental replication case, such as dumpling + TiCDC
- [x] 5. Add document about schema use scenario in Kafka sink. ref https://github.com/pingcap/ticdc/issues/626
- [x] 6. Add document about DDL reentrant restrictions and DDL related operation. related issue: https://github.com/pingcap/ticdc/issues/625 @amyangfei https://github.com/pingcap/docs-cn/pull/3723
- [ ] 7. Add document about sink customization 
- [x] 8. Add document about cyclic replication (What it is and how to use.) @overvenus https://github.com/pingcap/docs-cn/pull/3666
- [x] 9. Add document about how to upgrade CDC
- [x] 10. Add software and hardware recommendation @overvenus https://github.com/pingcap/docs-cn/pull/3676
- [x] 11. Add document about timezone error. ref: https://github.com/pingcap/ticdc/issues/165 @amyangfei https://github.com/pingcap/docs-cn/pull/3723
- [x] 12. Add more details about changefeed information
- [x] 13. Add FAQ about the problem: no data is replicated
- [ ] 14. Add document about the manual scheduling @leoppro P0
- [ ] 15. Add best practices about TiCDC usage scenario
- [x] 16. Add document about common failure case using Kafka sink, including `max.request.size` etc. @overvenus https://github.com/pingcap/docs-cn/pull/3882

**Comment by overvenus** [comment]
I take item 1 and item 8.

**Comment by amyangfei** [comment]
The document optimization will be tracked in other issue.
