### ISSUE TITLE
Tracking issue for engine removing dependency on etcd

### ISSUE THREAD

**Issue by gozssky** [pingcap/tiflow#6387]
## Background
Currently, our system relies on ETCD to support service discovery and leader election, and on MySQL to store metadata. To simplify the architecture of our system, we want to reduce the dependency on external services.

Our system is a typical master/worker architecture, all executors are connected to the server master. So we can implement the service discovery on the server master. And the leader election can also be implemented by MySQL. Therefore, we plan to remove the dependency on the ETCD.

## Development Task

- [x] https://github.com/pingcap/tiflow/issues/6388
- [x] https://github.com/pingcap/tiflow/issues/6867
- [x] Abstract leader election interface and support MySQL https://github.com/pingcap/tiflow/pull/6949
