### ISSUE TITLE
Tracking list for cancel job feature

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#6749]
### Is your feature request related to a problem?

Currently we have a simple pause job feature in server master, which relies on the availability of job master, but it is not robust in many scenarios.

### Describe the feature you'd like

- [ ] Design the independent job status layer, between upper logic and underlying master worker framework. The feature of job status layer contains
   - [x] Explicit job status, which will be exposed to OpenAPI
   - [x] Decouple its logic from master worker framework
   - [ ] Provide an intermedium to translate job status in master worker framework to job status layer.
- [x] Provide circuit breaker in case of job master restarts and fails for several times during short time.
- [x] Provide `StopImpl` callback in master worker framework.
- [ ] Add a way to cancel hanging job from the runtime perspective. (*hanging job* is a running job, it receives `OnCancel` callback but keeps running and doesn't exit.

#### Normal path

![image](https://user-images.githubusercontent.com/1527315/185560669-8de26b63-2ae9-4219-8f42-12535528c021.png)
source: https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

#### Fail path

![image](https://user-images.githubusercontent.com/1527315/185562387-92095a32-ae97-4318-aa08-b31c55385c9c.png)
source: https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

**Comment by lance6716** [comment]
please improve priority @amyangfei
