### ISSUE TITLE
Tracking issue for  migrating some DM tests to DFE

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#6776]
## P0
- [x] full_mode https://github.com/pingcap/tiflow/pull/6883
- [x] gbk https://github.com/pingcap/tiflow/pull/7186
- [x] new_collation_off https://github.com/pingcap/tiflow/pull/6857
- [x] print_status https://github.com/pingcap/tiflow/pull/7129
- [x] sql_mode https://github.com/pingcap/tiflow/pull/6951
- [x] sync_collation https://github.com/pingcap/tiflow/pull/6808
- [x] tls https://github.com/pingcap/tiflow/pull/6913

## P1

- [x] case_sensitive https://github.com/pingcap/tiflow/pull/6768
- [ ] check_task
- [ ] downstream_more_column
- [ ] gtid
- [ ] handle_error
- [ ] handle_error_2
- [ ] handle_error_3
- [ ] online_ddl
- [ ] s3_dumpling_lighting
- [ ] sequence_sharding
- [ ] sequence_sharding_removemeta
- [ ] shardddl1
- [ ] shardddl1_1
- [ ] shardddl2
- [ ] shardddl2_1
- [ ] shardddl3
- [ ] shardddl3_1
- [ ] shardddl4
- [ ] shardddl4_1
- [ ] shardddl_optimistic
- [ ] start_task
- [ ] tracker_ignored_ddl
- [ ] upstream_switch

## P2

- [ ] all_mode
  - [ ] test_expression_filter
  - [ ] test_regexpr_router
  - [ ] others（failpoint）
- [ ] binlog_999999
- [ ] downstream_diff_index
- [ ] drop_column_with_index
- [ ] expression_filter
- [ ] extend_column
- [ ] many_tables https://github.com/pingcap/tiflow/pull/6616
- [ ] validator_basic
- [ ] validator_checkpoint

## failpoint
- [ ] adjust_gtid（failpoint）
- [ ] async_checkpoint_flush（failpoint）
- [ ] checkpoint_transaction（failpoint）
- [ ] duplicate_event（failpoint）
- [ ] fake_rotate_event（failpoint）
- [ ] incremental_mode(failpoint)
- [ ] load_interrupt(failpoint)
- [ ] metrics(failpoint)
- [ ] safe_mode(failpoint)
- [ ] sequence_safe_mode(failpoint)
- [ ] sequence_sharding_optimistic(failpoint)
- [ ] sharding(failpoint)
- [ ] sharding2(failpoint)
