### ISSUE TITLE
Make TiCDC a completely alternative to TiDB-Binlog 

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#690]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB-Binlog is used mostly in Data replication, realtime backup & recovery, yet it has high availability drawbacks and is not able to handle large scale TiDB cluster, TiCDC could be a better alternative to TiDB-Binlog.

But currently the existing TiDB-Binlog usage scenario can't be migrated seamlessly, basically means users have to do some adaption, both in architecture and application to migrate from TiDB-Binlog to TiCDC.

In order to make the migration from TiDB-Binlog to TiCDC easier and more user-friendly, TiCDC should be more compatible with TiDB-Binlog, and implement several features that TiDB-Binlog has provided but TiCDC can't delivery now.

**TODO list**

- Features required
    - [x] 1.Support distinguish `update` and `insert` in a row changed event.
    - [x] 2.Support to provide old values in the row changed event, including old values in `delete` or `update` SQL.
    - [ ] 3.Provide a sink that can output data in the format of TiDB-Binlog transaction protobuf, in order the existing pb file consumer can be used without any application modification.
- Solution required
    - [ ] 4.Provide a full solution about how to migrate from TiDB-Binlog to TiCDC.

### Value description 

This is a very import feature, in all scenarios that replace TiDB-binlog with TiCDC 

### Value score 

* (TBD) / 5

### Workload estimation 

* total 55 person-day, still need 30 person-day(in 07-28)

### Time

GanttStart: 2020-07-01
GanttDue: 2020-08-31 
GanttProgress: 90%

task 1&2 must be done before due date

**Comment by scsldb** [comment]
Reason for reprioritization: development complete, testing in progress, more important current development tasks.
