### ISSUE TITLE
Support snapshot level consistent replication

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#691]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In many scenarios, users use TiCDC to backup data from cluster A to cluster B, and use cluster B as a plan-B if cluster A meets unrecoverable disaster.

Currently TiCDC has several drawbacks:

- If upstream PD cluster meets disaster, TiCDC can't replicate until upstream PD recovers. Besides as TiCDC has multiple captures and even in on processor DML execution is concurrent, so in this case, the downstream can't be mapped to a snapshot against upstream.
- If upstream TiKV meets disaster, some received data from upstream can't be replicated to downstream due to some resolved ts missing from regions.
- MySQL sink in TiCDC can't ensure downstream can be mapped to a snapshot against upstream  in real time, this is also the main point focused in https://github.com/pingcap/ticdc/issues/658

Note: This work will be a part of PITR

Related docs: [Support read_only Global Variable in TiDB](https://docs.google.com/document/d/17xKNFZIKKibIIfmIFEsqVtMQ0cEDgDpVdHvWtRY5NSQ/edit#)

**Task List**

- [ ] Support MySQL sink can replicate to a snapshot level consistent state when upstream meets a disaster

- [ ] Support log sink can replicate to a snapshot level consistent state even when upstream meets a disaster

- [x] [pingcap/ticdc#658](https://github.com/pingcap/ticdc/issues/658) Snapshot Level Consistency Replication in non-disaster scenario

**Progress Tracking**

- https://github.com/pingcap/ticdc/projects/10

**Describe alternatives you've considered:**

Have some possible solutions:

- use PD to coordinate to a consistent TSO, if upstream PD cluster is available
- add undo log mechanism, use it to recover downstream to a consistent TSO if upstream PD cluster is not available.

### Value description 

(TBD)

### Value score 

* (TBD) / 5

### Workload estimation 

* 40 person-day

### Time

GanttStart: 2020-09-01
GanttDue: 2020-10-31
GanttProgress: 20%

**Comment by amyangfei** [comment]
ref: https://github.com/pingcap/br/issues/325

**Comment by IANTHEREAL** [comment]
one solution - https://github.com/pingcap/tidb/issues/18426#issuecomment-659273685

**Comment by IANTHEREAL** [comment]
@amyangfei can you update this issue to current status, contain our newest plan

**Comment by amyangfei** [comment]
This feature has been implemented in https://github.com/pingcap/tiflow/issues/2351
