### ISSUE TITLE
Tracking issues for the grafana and prometheus metric

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#6985]
### Is your feature request related to a problem?

No

### Describe the feature you'd like

- [ ] Add basic grafana page for Tiflow
- [ ] Add a dm job list table
- [ ] Add some k8s variables to grafana dashboard for cloud deployment
- [ ] Add metrics for tiflow components
