### ISSUE TITLE
Tracking issue for improving code structure and abstraction

### ISSUE THREAD

**Issue by gozssky** [pingcap/tiflow#7619]
## Motivation

The current structure and abstraction of engine are not good enough, and it is hard to maintain and extend. This issue is used to track the improvement. It is a long-term issue, and we will split it into multiple issues. We will focus on the following aspects:
* master/worker abstraction
* executor runtime enhancement
* better structure for maintaining and testing

## Task List

- [x] #7695
- [ ] Do not embed `BaseXXX` in `XXXImpl`
- [ ] Refine master/worker interface naming
- [ ] Recheck [dig](https://github.com/uber-go/dig) usage, remove or refactor
