### ISSUE TITLE
Tracking issue for improving optimizing the engine's api design

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#7643]
# Task List
- [ ] opanapi @gozssky
- [ ] rpc @CharlesCheung96 
- [ ] solving the timeout problem
- [ ] solving resource management problems
- [ ] add time consuming statistics to the api

# opanapi
### P0
- [x] #7654
- [ ] parallel query jobMaster in `listjob`

# rpc
