### ISSUE TITLE
Tracking issue for scale-out single large table to multiple TiCDC instances

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#7720]
This project add the ability of scale-out of a single table to multiple TiCDC nodes. Let TiCDC support dynamically split and merge spans based on statistical data, including region count, write throughput, etc. Split and merge are just table scheduling, and with the help of two-phase scheduling, they have minimal impact on replication latency.

## Span Replication

- [x] https://github.com/pingcap/tiflow/pull/7722
- [x] https://github.com/pingcap/tiflow/pull/7723
- [x] https://github.com/pingcap/tiflow/pull/7731
- [x] https://github.com/pingcap/tiflow/pull/7793
- [x] https://github.com/pingcap/tiflow/pull/7806
- [x] https://github.com/pingcap/tiflow/pull/7832
- [x] https://github.com/pingcap/tiflow/pull/7833
- [x] https://github.com/pingcap/tiflow/pull/7838
- [x] https://github.com/pingcap/tiflow/pull/7880
- [x] https://github.com/pingcap/tiflow/pull/7909
- [x] https://github.com/pingcap/tiflow/pull/7916
- [x] https://github.com/pingcap/tiflow/pull/7978
- [x] https://github.com/pingcap/tiflow/pull/8010
- [ ] Unify variable names, rename table to tableSpan
- [x] https://github.com/pingcap/tiflow/pull/8021
- [x] https://github.com/pingcap/tiflow/pull/8070
- [x] https://github.com/pingcap/tiflow/pull/8100

### Support split span by write throughput

- [x] https://github.com/pingcap/tiflow/pull/8496
- [x] https://github.com/pingcap/tiflow/pull/8505

### Document

- [x] https://github.com/pingcap/docs-cn/pull/12693
- [x] https://github.com/pingcap/docs-cn/pull/13341
