### ISSUE TITLE
Follow up after the first milestone of dataflow engine with DM on Cloud

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#7728]
### Is your feature request related to a problem?

We have released DM on cloud with tiflow engine as the underlying framework, there remain some follow ups to make the feature better.

### Describe the feature you'd like

- [ ] Refine document of project
- [ ] Improve code structure, ref #7619 
- [ ] Dig into callback sequence
- [ ] p2p message accumulation issue.

## The future work

- [ ] ...
