### ISSUE TITLE
Tracking issue for MySQL sink performance diagnosis

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#8045]
### Is your feature request related to a problem?

MySQL sink is a key module for replicating data to MySQL protocol backends, in some scenarios it could meet performance bottleneck and propagate the performance problem to the whole cdc cluster. The bottle could happen in either backend side or MySQL sink side. This issue tries to make such problem diagnosable and easy to analyze the problem.

### Describe the feature you'd like

Break down to the following sub tasks
- [ ] Supports to fetch essential metrics stored in TiDB diagnose table.
- [ ] Add more diagnose Grafana monitoring according to the above metrics.
- [ ] Investigate whether TiCDC can reports some diagnose report.
