### ISSUE TITLE
Tracking issue for optimizing redo log

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#8056]
- [x] In owner, separate DDL dataflow to redoManager and DDLsink. And calculate resolvedTs of redo module based on DDL and DML progress.
- [x] #8361
- [x] Refactor redo applier based on sinkV2 to improve downstream write concurrency and reduce RTO. 
- [x] [Support use memory to cache temporary files in redo log](https://github.com/pingcap/tiflow/issues/8086).
- [x] https://github.com/pingcap/tiflow/issues/8361
- [x] https://github.com/pingcap/tiflow/pull/8407
- [x] #8963
- [x] In sinkManager, ensure that redo log is not blocked by the sink related error. 
- [x] #9313
- [ ] Refactor redo log module based on the cloud storage sink.

**Comment by nongfushanquan** [comment]
Support use memory to cache temporary files in redo log. --- this feature has been done in the master and 6.5
