### ISSUE TITLE
Tracking issue for cleaning up dead code in TiCDC code base.

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#8470]
There are some exported variables and types that are left by TiCDC evolution and become essentially dead code. We should clean them up.

There is a script for find such code (note: it might output false positive results!)

```bash
PKG=$1 # Fill your packages. go list ./... | cut -d'/' -f4- | grep -E '^(cdc|pkg)'
grep -oE "type [A-Z][a-zA-Z0-9]+ struct" $PKG/*.go | grep -oE "[A-Z][a-zA-Z0-9]+" | while read line; do { \
    f=$(grep $line pkg/**/*.go cdc/**/*.go | grep -v "$PKG" | awk -F ':' '{print $1}' | uniq | wc -l) ; \
    if [ $f -lt 2 ]; then { echo $line } fi ; \
} done; 
```

- [ ] https://github.com/pingcap/tiflow/issues/8468
- [ ] https://github.com/pingcap/tiflow/issues/8449
- [ ] https://github.com/pingcap/tiflow/issues/8417
- [ ] https://github.com/pingcap/tiflow/issues/8404

**Comment by overvenus** [comment]
Dup https://github.com/pingcap/tiflow/issues/4954
